// ═══════════════════════════════════════════════════════
// QUESTIFY — Mock Data
// Extensive, realistic data for demo & development
// ═══════════════════════════════════════════════════════

import type {
  User,
  Quiz,
  FlashcardDeck,
  UploadedFile,
  Achievement,
  LeaderboardEntry,
  Battle,
  RevisionTopic,
  Activity,
  StudyDataPoint,
  AccuracyDataPoint,
} from '@/types';

// ─── Current User ─────────────────────────────────────

export const currentUser: User = {
  id: 'user_001',
  name: 'Arjun Mehta',
  email: 'arjun.mehta@email.com',
  avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Arjun&backgroundColor=0B1020',
  role: 'aspirant',
  plan: 'pro',
  xp: 2450,
  xpToNextLevel: 2000,
  level: 3,
  streak: 12,
  longestStreak: 18,
  quizzesCompleted: 47,
  accuracy: 78,
  studyTimeMinutes: 1260,
  topicsMastered: 14,
  joinedAt: '2026-01-15T09:00:00Z',
  stats: {
    totalXP: 2450,
    currentStreak: 12,
    longestStreak: 18,
  },
  preferences: {
    dailyGoalMinutes: 45,
    examType: 'JEE Mains',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    notifications: true,
    darkMode: true,
  },
};

// ─── Mock Quizzes ─────────────────────────────────────

export const mockQuizzes: Quiz[] = [
  // ── Physics: Newton's Laws ──
  {
    id: 'quiz_001',
    title: "Newton's Laws of Motion",
    subject: 'Physics',
    topic: 'Mechanics',
    difficulty: 'medium',
    questionCount: 8,
    timeLimit: 600,
    xpReward: 75,
    createdAt: '2026-06-10T14:30:00Z',
    sourceFile: 'Physics_Chapter3.pdf',
    questions: [
      {
        id: 'q_001_1',
        text: "A body of mass 5 kg is acted upon by two perpendicular forces of 8 N and 6 N. What is the magnitude of the acceleration?",
        options: ['1.0 m/s²', '2.0 m/s²', '2.8 m/s²', '10.0 m/s²'],
        correctAnswer: 1,
        explanation: 'The resultant force is √(8² + 6²) = √(64 + 36) = √100 = 10 N. By Newton\'s second law, a = F/m = 10/5 = 2.0 m/s².',
        difficulty: 'medium',
      },
      {
        id: 'q_001_2',
        text: "Newton's first law of motion defines which of the following?",
        options: ['Force', 'Inertia', 'Energy', 'Momentum'],
        correctAnswer: 1,
        explanation: "Newton's first law is also known as the law of inertia. It states that a body continues in its state of rest or uniform motion unless acted upon by an external force, thereby defining inertia.",
        difficulty: 'easy',
      },
      {
        id: 'q_001_3',
        text: 'A 2000 kg car accelerates from rest to 20 m/s in 10 seconds. What is the net force acting on the car?',
        options: ['2000 N', '4000 N', '10000 N', '40000 N'],
        correctAnswer: 1,
        explanation: 'Acceleration a = (v - u) / t = (20 - 0) / 10 = 2 m/s². Net force F = ma = 2000 × 2 = 4000 N.',
        difficulty: 'easy',
      },
      {
        id: 'q_001_4',
        text: 'A bullet of mass 50 g is fired from a gun of mass 4 kg with a velocity of 200 m/s. What is the recoil velocity of the gun?',
        options: ['2.5 m/s', '5.0 m/s', '10.0 m/s', '1.25 m/s'],
        correctAnswer: 0,
        explanation: "By Newton's third law and conservation of momentum: m₁v₁ = m₂v₂. So 0.05 × 200 = 4 × v₂. Therefore v₂ = 10/4 = 2.5 m/s.",
        difficulty: 'medium',
      },
      {
        id: 'q_001_5',
        text: 'An object of mass 3 kg is at rest. A force of 12 N is applied for 4 seconds. What is the velocity attained by the object?',
        options: ['4 m/s', '8 m/s', '12 m/s', '16 m/s'],
        correctAnswer: 3,
        explanation: 'a = F/m = 12/3 = 4 m/s². Using v = u + at = 0 + 4 × 4 = 16 m/s.',
        difficulty: 'easy',
      },
      {
        id: 'q_001_6',
        text: 'Two blocks of masses 3 kg and 2 kg are placed in contact on a frictionless surface. A force of 10 N is applied on the 3 kg block. What is the force exerted by the 3 kg block on the 2 kg block?',
        options: ['2 N', '4 N', '6 N', '10 N'],
        correctAnswer: 1,
        explanation: 'The acceleration of the system is a = F / (m₁ + m₂) = 10/5 = 2 m/s². The force on the 2 kg block is F = m₂ × a = 2 × 2 = 4 N.',
        difficulty: 'hard',
      },
      {
        id: 'q_001_7',
        text: 'A lift is moving upward with an acceleration of 2 m/s². What is the apparent weight of a 60 kg person inside the lift? (g = 10 m/s²)',
        options: ['480 N', '600 N', '720 N', '660 N'],
        correctAnswer: 2,
        explanation: 'Apparent weight = m(g + a) = 60 × (10 + 2) = 60 × 12 = 720 N.',
        difficulty: 'medium',
      },
      {
        id: 'q_001_8',
        text: 'A body moves in a circular path of radius 5 m with a speed of 10 m/s. What is the centripetal acceleration?',
        options: ['2 m/s²', '10 m/s²', '20 m/s²', '50 m/s²'],
        correctAnswer: 2,
        explanation: 'Centripetal acceleration a = v²/r = (10)²/5 = 100/5 = 20 m/s².',
        difficulty: 'medium',
      },
    ],
  },

  // ── Chemistry: Periodic Table ──
  {
    id: 'quiz_002',
    title: 'Periodic Table & Elements',
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'easy',
    questionCount: 7,
    timeLimit: 420,
    xpReward: 50,
    createdAt: '2026-06-11T10:00:00Z',
    questions: [
      {
        id: 'q_002_1',
        text: 'Which element has the highest electronegativity?',
        options: ['Oxygen', 'Fluorine', 'Chlorine', 'Nitrogen'],
        correctAnswer: 1,
        explanation: 'Fluorine has the highest electronegativity (3.98 on the Pauling scale) because it has a small atomic radius and a high effective nuclear charge, attracting bonding electrons very strongly.',
        difficulty: 'easy',
      },
      {
        id: 'q_002_2',
        text: 'Which block of the periodic table contains the transition metals?',
        options: ['s-block', 'p-block', 'd-block', 'f-block'],
        correctAnswer: 2,
        explanation: 'Transition metals are elements in which the d-orbitals are being filled. They occupy the d-block (Groups 3-12) of the periodic table.',
        difficulty: 'easy',
      },
      {
        id: 'q_002_3',
        text: 'The element with atomic number 20 belongs to which group?',
        options: ['Group 1', 'Group 2', 'Group 18', 'Group 13'],
        correctAnswer: 1,
        explanation: 'Atomic number 20 is Calcium (Ca), which has the electron configuration [Ar] 4s². Since the last electrons fill the s-orbital, it belongs to Group 2 (alkaline earth metals).',
        difficulty: 'easy',
      },
      {
        id: 'q_002_4',
        text: 'Which of the following has the largest atomic radius?',
        options: ['Na', 'Mg', 'Al', 'K'],
        correctAnswer: 3,
        explanation: 'Potassium (K) has the largest atomic radius because it is in Period 4, farther down Group 1. Atomic radius increases down a group and decreases across a period.',
        difficulty: 'medium',
      },
      {
        id: 'q_002_5',
        text: 'Lanthanide contraction is caused by:',
        options: [
          'Poor shielding by 4f electrons',
          'Expansion of the 5d orbitals',
          'High ionization energy',
          'Increase in atomic mass',
        ],
        correctAnswer: 0,
        explanation: 'Lanthanide contraction occurs because 4f electrons are poor shielders of nuclear charge. As the atomic number increases across the lanthanides, the nuclear charge increases but shielding remains weak, causing atomic radii to decrease.',
        difficulty: 'hard',
      },
      {
        id: 'q_002_6',
        text: 'Noble gases have a stable configuration due to:',
        options: [
          'Completely filled s-orbitals',
          'Completely filled valence shell',
          'Large atomic size',
          'High ionization potential only',
        ],
        correctAnswer: 1,
        explanation: 'Noble gases have completely filled valence shells (ns²np⁶ for all except He which is 1s²), giving them exceptional stability and very low chemical reactivity.',
        difficulty: 'easy',
      },
      {
        id: 'q_002_7',
        text: 'The correct order of first ionization energy is:',
        options: ['B < Be < N < O', 'Be < B < N < O', 'B < Be < O < N', 'Be < B < O < N'],
        correctAnswer: 2,
        explanation: 'B (5.39) < Be (9.32) < O (13.62) < N (14.53). Beryllium has a higher IE than Boron due to its stable fully filled 2s². Nitrogen has a higher IE than Oxygen due to its stable half-filled 2p³ configuration.',
        difficulty: 'hard',
      },
    ],
  },

  // ── Mathematics: Calculus ──
  {
    id: 'quiz_003',
    title: 'Differential Calculus',
    subject: 'Mathematics',
    topic: 'Calculus',
    difficulty: 'hard',
    questionCount: 6,
    timeLimit: 720,
    xpReward: 100,
    createdAt: '2026-06-12T16:00:00Z',
    sourceFile: 'Calculus_Notes.pdf',
    questions: [
      {
        id: 'q_003_1',
        text: 'What is the derivative of f(x) = x³ · sin(x)?',
        options: [
          '3x² · sin(x) + x³ · cos(x)',
          '3x² · cos(x)',
          'x³ · cos(x) - 3x² · sin(x)',
          '3x² · sin(x) - x³ · cos(x)',
        ],
        correctAnswer: 0,
        explanation: "Using the product rule: d/dx[u·v] = u'·v + u·v'. Here u = x³, v = sin(x). So f'(x) = 3x²·sin(x) + x³·cos(x).",
        difficulty: 'medium',
      },
      {
        id: 'q_003_2',
        text: 'The value of lim(x→0) [sin(3x) / x] is:',
        options: ['0', '1', '3', '1/3'],
        correctAnswer: 2,
        explanation: 'lim(x→0) [sin(3x)/x] = lim(x→0) [3 · sin(3x)/(3x)] = 3 · lim(3x→0) [sin(3x)/(3x)] = 3 × 1 = 3, using the standard limit sin(θ)/θ → 1.',
        difficulty: 'easy',
      },
      {
        id: 'q_003_3',
        text: 'If y = eˣ · ln(x), then dy/dx at x = 1 is:',
        options: ['e', 'e + 1', '1', '0'],
        correctAnswer: 0,
        explanation: "Using product rule: dy/dx = eˣ·ln(x) + eˣ·(1/x). At x = 1: dy/dx = e¹·ln(1) + e¹·(1/1) = e·0 + e·1 = e.",
        difficulty: 'medium',
      },
      {
        id: 'q_003_4',
        text: 'The function f(x) = x³ - 3x² + 4 has a local maximum at:',
        options: ['x = 0', 'x = 2', 'x = -2', 'x = 1'],
        correctAnswer: 0,
        explanation: "f'(x) = 3x² - 6x = 3x(x - 2) = 0 gives x = 0 and x = 2. f''(x) = 6x - 6. At x = 0: f''(0) = -6 < 0, so x = 0 is a local maximum. At x = 2: f''(2) = 6 > 0, so x = 2 is a local minimum.",
        difficulty: 'hard',
      },
      {
        id: 'q_003_5',
        text: "What is the integral of ∫ 2x · eˣ² dx?",
        options: ['eˣ² + C', '2eˣ² + C', 'x² · eˣ² + C', 'eˣ² / 2 + C'],
        correctAnswer: 0,
        explanation: "Let u = x². Then du = 2x dx. So ∫ 2x·eˣ² dx = ∫ eᵘ du = eᵘ + C = eˣ² + C.",
        difficulty: 'medium',
      },
      {
        id: 'q_003_6',
        text: "Rolle's theorem is applicable for f(x) = x² - 4x + 3 in the interval:",
        options: ['[0, 4]', '[1, 3]', '[0, 3]', '[-1, 1]'],
        correctAnswer: 1,
        explanation: "For Rolle's theorem, f(a) = f(b). f(1) = 1 - 4 + 3 = 0 and f(3) = 9 - 12 + 3 = 0. So f(1) = f(3) = 0, and f is continuous and differentiable on [1, 3]. The theorem applies with c = 2 where f'(c) = 0.",
        difficulty: 'hard',
      },
    ],
  },

  // ── Biology: Cell Biology ──
  {
    id: 'quiz_004',
    title: 'Cell Structure & Function',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'easy',
    questionCount: 7,
    timeLimit: 420,
    xpReward: 50,
    createdAt: '2026-06-13T09:15:00Z',
    questions: [
      {
        id: 'q_004_1',
        text: 'Which organelle is known as the powerhouse of the cell?',
        options: ['Ribosome', 'Mitochondria', 'Golgi apparatus', 'Endoplasmic reticulum'],
        correctAnswer: 1,
        explanation: 'Mitochondria are called the powerhouse of the cell because they produce ATP (adenosine triphosphate) through oxidative phosphorylation and the citric acid cycle, providing energy for cellular activities.',
        difficulty: 'easy',
      },
      {
        id: 'q_004_2',
        text: 'The fluid mosaic model describes the structure of:',
        options: ['Cell wall', 'Nuclear membrane', 'Plasma membrane', 'Mitochondrial matrix'],
        correctAnswer: 2,
        explanation: "The fluid mosaic model, proposed by Singer and Nicolson in 1972, describes the plasma membrane as a dynamic structure with a phospholipid bilayer and embedded proteins that can move laterally, giving it a 'mosaic' pattern in a 'fluid' environment.",
        difficulty: 'easy',
      },
      {
        id: 'q_004_3',
        text: 'Which of the following is NOT a function of the Golgi apparatus?',
        options: ['Protein modification', 'Lipid synthesis', 'Protein synthesis', 'Vesicle formation'],
        correctAnswer: 2,
        explanation: 'Protein synthesis occurs at ribosomes (both free and on rough ER). The Golgi apparatus modifies, sorts, and packages proteins and lipids into vesicles for transport.',
        difficulty: 'medium',
      },
      {
        id: 'q_004_4',
        text: 'Lysosomes are formed by:',
        options: ['Mitochondria', 'Nucleus', 'Golgi apparatus', 'Smooth ER'],
        correctAnswer: 2,
        explanation: 'Lysosomes are membrane-bound vesicles that bud off from the trans-Golgi network. They contain hydrolytic enzymes that are synthesized by the rough ER and processed by the Golgi apparatus.',
        difficulty: 'medium',
      },
      {
        id: 'q_004_5',
        text: 'The 9+2 arrangement of microtubules is found in:',
        options: ['Centrioles', 'Cilia and flagella', 'Spindle fibers', 'Microvilli'],
        correctAnswer: 1,
        explanation: 'Cilia and flagella have a characteristic 9+2 axonemal arrangement — nine outer doublet microtubules surrounding two central singlet microtubules. Centrioles have a 9+0 arrangement (nine triplets, no central pair).',
        difficulty: 'hard',
      },
      {
        id: 'q_004_6',
        text: 'In prokaryotic cells, the genetic material is located in the:',
        options: ['Nucleus', 'Nucleoid', 'Mitochondria', 'Ribosome'],
        correctAnswer: 1,
        explanation: 'Prokaryotic cells lack a membrane-bound nucleus. Their DNA is located in a region called the nucleoid, which is not enclosed by a nuclear membrane.',
        difficulty: 'easy',
      },
      {
        id: 'q_004_7',
        text: 'Which cellular junction allows direct communication between adjacent plant cells?',
        options: ['Tight junctions', 'Gap junctions', 'Plasmodesmata', 'Desmosomes'],
        correctAnswer: 2,
        explanation: 'Plasmodesmata are microscopic channels that connect adjacent plant cells, allowing transport of molecules and communication. Gap junctions serve a similar role in animal cells.',
        difficulty: 'medium',
      },
    ],
  },

  // ── History: Indian Independence ──
  {
    id: 'quiz_005',
    title: 'Indian Independence Movement',
    subject: 'History',
    topic: 'Modern Indian History',
    difficulty: 'medium',
    questionCount: 6,
    timeLimit: 480,
    xpReward: 75,
    createdAt: '2026-06-14T11:00:00Z',
    questions: [
      {
        id: 'q_005_1',
        text: 'The Non-Cooperation Movement was launched in which year?',
        options: ['1919', '1920', '1930', '1942'],
        correctAnswer: 1,
        explanation: "The Non-Cooperation Movement was launched by Mahatma Gandhi on August 1, 1920, in response to the Jallianwala Bagh massacre and the oppressive Rowlatt Act. It was the first mass movement against British rule.",
        difficulty: 'easy',
      },
      {
        id: 'q_005_2',
        text: 'The Dandi March was associated with which movement?',
        options: ['Quit India Movement', 'Non-Cooperation Movement', 'Civil Disobedience Movement', 'Swadeshi Movement'],
        correctAnswer: 2,
        explanation: 'The Dandi March (Salt March) in March-April 1930 launched the Civil Disobedience Movement. Gandhi walked 388 km from Sabarmati Ashram to the coastal village of Dandi to make salt, defying the British salt tax.',
        difficulty: 'easy',
      },
      {
        id: 'q_005_3',
        text: "Who gave the slogan 'Do or Die' during the Quit India Movement?",
        options: ['Subhas Chandra Bose', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Sardar Patel'],
        correctAnswer: 2,
        explanation: "Mahatma Gandhi gave the famous slogan 'Do or Die' (Karo ya Maro) at the All India Congress Committee session in Bombay on August 8, 1942, marking the start of the Quit India Movement.",
        difficulty: 'easy',
      },
      {
        id: 'q_005_4',
        text: 'The Indian National Congress was founded in which year?',
        options: ['1880', '1885', '1890', '1905'],
        correctAnswer: 1,
        explanation: "The Indian National Congress was founded on December 28, 1885, at Gokuldas Tejpal Sanskrit College in Bombay. A.O. Hume, a retired British civil servant, played a key role in its formation.",
        difficulty: 'medium',
      },
      {
        id: 'q_005_5',
        text: 'The Partition of Bengal in 1905 was carried out by:',
        options: ['Lord Irwin', 'Lord Curzon', 'Lord Mountbatten', 'Lord Ripon'],
        correctAnswer: 1,
        explanation: 'Lord Curzon, the Viceroy of India, announced the Partition of Bengal on July 19, 1905 (effective October 16, 1905). It divided Bengal along religious lines, creating East Bengal (Muslim majority) and West Bengal (Hindu majority).',
        difficulty: 'medium',
      },
      {
        id: 'q_005_6',
        text: 'The Jallianwala Bagh massacre took place on:',
        options: ['April 13, 1919', 'March 12, 1930', 'August 15, 1947', 'January 26, 1950'],
        correctAnswer: 0,
        explanation: 'The Jallianwala Bagh massacre occurred on April 13, 1919, in Amritsar. General Dyer ordered troops to fire on a peaceful gathering, killing hundreds. This event was a turning point in the Indian independence movement.',
        difficulty: 'medium',
      },
    ],
  },

  // ── Computer Science: Data Structures ──
  {
    id: 'quiz_006',
    title: 'Data Structures & Algorithms',
    subject: 'Computer Science',
    topic: 'DSA Fundamentals',
    difficulty: 'hard',
    questionCount: 8,
    timeLimit: 720,
    xpReward: 100,
    createdAt: '2026-06-15T08:30:00Z',
    sourceFile: 'DSA_Notes.md',
    questions: [
      {
        id: 'q_006_1',
        text: 'What is the time complexity of searching in a balanced Binary Search Tree?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correctAnswer: 1,
        explanation: 'In a balanced BST, each comparison eliminates half the remaining nodes. The height of a balanced BST is O(log n), so search, insert, and delete operations all take O(log n) time.',
        difficulty: 'easy',
      },
      {
        id: 'q_006_2',
        text: 'Which data structure uses LIFO (Last In First Out) principle?',
        options: ['Queue', 'Stack', 'Linked List', 'Heap'],
        correctAnswer: 1,
        explanation: 'A Stack follows LIFO — the last element pushed is the first one popped. Common uses include function call stacks, expression evaluation, and undo operations.',
        difficulty: 'easy',
      },
      {
        id: 'q_006_3',
        text: 'The worst-case time complexity of QuickSort is:',
        options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'],
        correctAnswer: 1,
        explanation: "QuickSort's worst case O(n²) occurs when the pivot is always the smallest or largest element (e.g., already sorted array with first element as pivot). This creates maximally unbalanced partitions. The average case is O(n log n).",
        difficulty: 'medium',
      },
      {
        id: 'q_006_4',
        text: 'Which traversal of a BST produces a sorted sequence?',
        options: ['Preorder', 'Inorder', 'Postorder', 'Level-order'],
        correctAnswer: 1,
        explanation: 'Inorder traversal (Left → Root → Right) of a BST always produces elements in sorted ascending order. This is because the left subtree contains smaller values and the right subtree contains larger values.',
        difficulty: 'easy',
      },
      {
        id: 'q_006_5',
        text: 'What is the space complexity of Merge Sort?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
        correctAnswer: 2,
        explanation: 'Merge Sort requires O(n) auxiliary space for the temporary arrays used during the merge step. While the recursion stack uses O(log n) space, the dominant term is O(n) for the merge operation.',
        difficulty: 'medium',
      },
      {
        id: 'q_006_6',
        text: 'In a hash table with open addressing, what is the load factor formula?',
        options: ['n × m', 'n / m', 'm / n', 'n + m'],
        correctAnswer: 1,
        explanation: 'Load factor α = n/m, where n is the number of stored elements and m is the number of slots. A load factor > 0.7 typically triggers resizing for performance.',
        difficulty: 'medium',
      },
      {
        id: 'q_006_7',
        text: 'Dijkstra\'s algorithm does NOT work correctly with:',
        options: [
          'Directed graphs',
          'Undirected graphs',
          'Negative edge weights',
          'Weighted graphs',
        ],
        correctAnswer: 2,
        explanation: "Dijkstra's algorithm assumes all edge weights are non-negative. With negative edges, a previously finalized shortest path could be shortened by a negative edge, violating the greedy property. Use Bellman-Ford for negative weights.",
        difficulty: 'hard',
      },
      {
        id: 'q_006_8',
        text: 'The minimum number of nodes in an AVL tree of height h is given by:',
        options: ['2ʰ - 1', 'N(h) = N(h-1) + N(h-2) + 1', 'h²', '2h + 1'],
        correctAnswer: 1,
        explanation: 'The minimum number of nodes follows the recurrence N(h) = N(h-1) + N(h-2) + 1, with N(0) = 1 and N(1) = 2. This is similar to Fibonacci numbers, giving the sparsest possible AVL tree.',
        difficulty: 'hard',
      },
    ],
  },
];

// ─── Mock Flashcard Decks ─────────────────────────────

export const mockFlashcardDecks: FlashcardDeck[] = [
  {
    id: 'deck_001',
    title: 'Organic Chemistry Reactions',
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    cardCount: 6,
    mastered: 2,
    lastReviewed: '2026-06-16T06:00:00Z',
    createdAt: '2026-06-01T10:00:00Z',
    cards: [
      {
        id: 'fc_001_1',
        front: "What is Markovnikov's rule?",
        back: "In the addition of HX to an unsymmetrical alkene, the hydrogen atom adds to the carbon with MORE hydrogen atoms (less substituted carbon), and the halide (X) adds to the MORE substituted carbon. This is because the more stable carbocation intermediate forms at the more substituted position.",
        status: 'mastered',
        bookmarked: true,
      },
      {
        id: 'fc_001_2',
        front: 'What is the Wurtz reaction?',
        back: 'The Wurtz reaction involves coupling two alkyl halides using metallic sodium in dry ether to form a higher alkane:\n\n2R-X + 2Na → R-R + 2NaX\n\nLimitation: Works best with primary alkyl halides. Mixed Wurtz gives three products.',
        status: 'mastered',
        bookmarked: false,
      },
      {
        id: 'fc_001_3',
        front: 'Explain the SN1 mechanism.',
        back: 'SN1 (Substitution Nucleophilic Unimolecular) is a two-step mechanism:\n\n1. Ionization: The leaving group departs, forming a carbocation\n2. Nucleophilic attack: The nucleophile attacks the planar carbocation\n\nRate = k[substrate]. Favored by: tertiary substrates, polar protic solvents, weak nucleophiles. Produces racemic mixture.',
        status: 'learning',
        bookmarked: true,
      },
      {
        id: 'fc_001_4',
        front: 'What is a Grignard reagent? How is it prepared?',
        back: 'A Grignard reagent (R-MgX) is an organomagnesium halide. Prepared by reacting an alkyl/aryl halide with magnesium metal in dry ether:\n\nR-X + Mg → R-MgX (dry ether)\n\nHighly reactive nucleophile. Reacts with water, CO₂, aldehydes, ketones, and esters. Must be kept anhydrous.',
        status: 'learning',
        bookmarked: false,
      },
      {
        id: 'fc_001_5',
        front: 'Define electrophilic aromatic substitution (EAS).',
        back: 'EAS is a reaction where an electrophile replaces a hydrogen on an aromatic ring. Steps:\n\n1. Generation of the electrophile (E⁺)\n2. Electrophilic attack → arenium ion (σ-complex)\n3. Deprotonation to restore aromaticity\n\nExamples: Nitration (HNO₃/H₂SO₄), Halogenation (X₂/FeX₃), Friedel-Crafts (RX or RCOCl/AlCl₃).',
        status: 'new',
        bookmarked: false,
      },
      {
        id: 'fc_001_6',
        front: 'What is the difference between elimination E1 and E2?',
        back: 'E1: Two-step, forms carbocation intermediate. Rate = k[substrate]. Favored by tertiary substrates, weak bases, polar protic solvents.\n\nE2: One-step, concerted. Rate = k[substrate][base]. Requires anti-periplanar geometry. Favored by strong bases, primary substrates, high temperature.\n\nBoth produce alkenes. E2 is stereospecific (anti elimination).',
        status: 'new',
        bookmarked: false,
      },
    ],
  },

  {
    id: 'deck_002',
    title: 'Physics Formulas — Electromagnetism',
    subject: 'Physics',
    topic: 'Electromagnetism',
    cardCount: 5,
    mastered: 1,
    lastReviewed: '2026-06-15T18:30:00Z',
    createdAt: '2026-06-05T14:00:00Z',
    cards: [
      {
        id: 'fc_002_1',
        front: "State Coulomb's Law with formula.",
        back: "Coulomb's Law: The electrostatic force between two point charges is directly proportional to the product of charges and inversely proportional to the square of the distance between them.\n\nF = kq₁q₂/r²\n\nwhere k = 1/(4πε₀) = 9 × 10⁹ N·m²/C²",
        status: 'mastered',
        bookmarked: true,
      },
      {
        id: 'fc_002_2',
        front: "State Gauss's Law.",
        back: "Gauss's Law: The total electric flux through a closed surface is equal to the net charge enclosed divided by the permittivity of free space.\n\nΦ = ∮ E⃗·dA⃗ = Q_enc / ε₀\n\nUseful for calculating electric fields of symmetric charge distributions (spherical, cylindrical, planar).",
        status: 'learning',
        bookmarked: false,
      },
      {
        id: 'fc_002_3',
        front: 'What is the Biot-Savart Law?',
        back: 'The Biot-Savart Law gives the magnetic field dB due to a small current element Idl⃗:\n\ndB⃗ = (μ₀/4π) · (Idl⃗ × r̂)/r²\n\nwhere μ₀ = 4π × 10⁻⁷ T·m/A is the permeability of free space. Used to find B for straight wires, circular loops, and solenoids.',
        status: 'learning',
        bookmarked: true,
      },
      {
        id: 'fc_002_4',
        front: "Write Faraday's Law of electromagnetic induction.",
        back: "Faraday's Law: The induced EMF in a circuit is equal to the negative rate of change of magnetic flux through the circuit.\n\nε = -dΦ_B/dt\n\nFor N turns: ε = -N(dΦ_B/dt)\n\nLenz's Law: The induced current opposes the change that produces it (explains the negative sign).",
        status: 'new',
        bookmarked: false,
      },
      {
        id: 'fc_002_5',
        front: "State Ampère's Circuital Law (with Maxwell's correction).",
        back: "Ampère's Law (modified): The line integral of B⃗ around a closed loop equals μ₀ times the total current (conduction + displacement) through the loop.\n\n∮ B⃗·dl⃗ = μ₀(I_c + ε₀ · dΦ_E/dt)\n\nMaxwell added the displacement current term ε₀(dΦ_E/dt) to account for changing electric fields, which was crucial for predicting electromagnetic waves.",
        status: 'new',
        bookmarked: false,
      },
    ],
  },

  {
    id: 'deck_003',
    title: 'Mathematical Theorems & Proofs',
    subject: 'Mathematics',
    topic: 'Theorems',
    cardCount: 5,
    mastered: 3,
    lastReviewed: '2026-06-16T05:00:00Z',
    createdAt: '2026-05-20T12:00:00Z',
    cards: [
      {
        id: 'fc_003_1',
        front: "State the Mean Value Theorem.",
        back: "If f is continuous on [a,b] and differentiable on (a,b), then there exists at least one c ∈ (a,b) such that:\n\nf'(c) = [f(b) - f(a)] / (b - a)\n\nGeometrically: there is a point where the tangent is parallel to the secant line joining (a,f(a)) and (b,f(b)).",
        status: 'mastered',
        bookmarked: true,
      },
      {
        id: 'fc_003_2',
        front: "State the Fundamental Theorem of Calculus.",
        back: "Part 1: If f is continuous on [a,b] and F(x) = ∫ₐˣ f(t)dt, then F'(x) = f(x).\n\nPart 2: If F is any antiderivative of f on [a,b], then:\n∫ₐᵇ f(x)dx = F(b) - F(a)\n\nThis connects differentiation and integration as inverse operations.",
        status: 'mastered',
        bookmarked: true,
      },
      {
        id: 'fc_003_3',
        front: "State L'Hôpital's Rule.",
        back: "If lim(x→a) f(x)/g(x) gives 0/0 or ∞/∞ (indeterminate form), and f and g are differentiable near a with g'(x) ≠ 0, then:\n\nlim(x→a) f(x)/g(x) = lim(x→a) f'(x)/g'(x)\n\nprovided the right-hand limit exists. Can be applied repeatedly for persistent indeterminate forms.",
        status: 'mastered',
        bookmarked: false,
      },
      {
        id: 'fc_003_4',
        front: "State Taylor's Theorem.",
        back: "If f has n+1 continuous derivatives on an interval containing a, then for any x in that interval:\n\nf(x) = f(a) + f'(a)(x-a) + f''(a)(x-a)²/2! + ... + fⁿ(a)(x-a)ⁿ/n! + Rₙ(x)\n\nwhere Rₙ is the remainder term. When a = 0, it's called a Maclaurin series.",
        status: 'learning',
        bookmarked: false,
      },
      {
        id: 'fc_003_5',
        front: "What is the Intermediate Value Theorem?",
        back: "If f is continuous on [a,b] and k is any value between f(a) and f(b), then there exists at least one c ∈ (a,b) such that f(c) = k.\n\nKey application: Proving existence of roots. If f(a) < 0 and f(b) > 0 (or vice versa), then f has at least one root in (a,b).",
        status: 'new',
        bookmarked: false,
      },
    ],
  },

  {
    id: 'deck_004',
    title: 'Computer Science — Sorting Algorithms',
    subject: 'Computer Science',
    topic: 'Algorithms',
    cardCount: 6,
    mastered: 0,
    createdAt: '2026-06-12T16:00:00Z',
    cards: [
      {
        id: 'fc_004_1',
        front: 'Explain Merge Sort with its time complexity.',
        back: 'Merge Sort is a divide-and-conquer algorithm:\n\n1. Divide array into two halves\n2. Recursively sort each half\n3. Merge the sorted halves\n\nTime: O(n log n) — all cases\nSpace: O(n) — for the merge step\nStable: Yes\n\nBest for: linked lists, external sorting, guaranteed O(n log n).',
        status: 'new',
        bookmarked: true,
      },
      {
        id: 'fc_004_2',
        front: 'What is the difference between BFS and DFS?',
        back: 'BFS (Breadth-First Search):\n- Uses Queue\n- Level-by-level traversal\n- Finds shortest path (unweighted)\n- Space: O(V) [width of graph]\n\nDFS (Depth-First Search):\n- Uses Stack (or recursion)\n- Goes deep before backtracking\n- Used for cycle detection, topological sort\n- Space: O(V) [depth of graph]',
        status: 'new',
        bookmarked: false,
      },
      {
        id: 'fc_004_3',
        front: 'What is Dynamic Programming?',
        back: 'Dynamic Programming (DP) solves problems by breaking them into overlapping subproblems and storing their solutions.\n\nTwo approaches:\n1. Top-down (Memoization): Recursive with cache\n2. Bottom-up (Tabulation): Iterative, fill table\n\nRequirements:\n- Optimal substructure\n- Overlapping subproblems\n\nExamples: Fibonacci, Knapsack, LCS, Edit Distance.',
        status: 'new',
        bookmarked: false,
      },
      {
        id: 'fc_004_4',
        front: 'Explain the concept of amortized time complexity.',
        back: 'Amortized analysis averages the time per operation over a sequence of operations, even if some individual operations are expensive.\n\nExample: Dynamic Array push\n- Most pushes: O(1)\n- Occasional resize: O(n)\n- Amortized per push: O(1)\n\nMethods: Aggregate, Accounting, Potential. Amortized ≠ Average case (amortized is worst-case guaranteed over n operations).',
        status: 'new',
        bookmarked: false,
      },
      {
        id: 'fc_004_5',
        front: 'What is a Red-Black Tree?',
        back: 'A Red-Black Tree is a self-balancing BST with these properties:\n\n1. Every node is red or black\n2. Root is black\n3. All leaves (NIL) are black\n4. Red node children must be black\n5. All paths from node to leaves have equal black nodes\n\nHeight: O(log n). Operations: O(log n).\nUsed in: Java TreeMap, C++ std::map, Linux CFS scheduler.',
        status: 'new',
        bookmarked: true,
      },
      {
        id: 'fc_004_6',
        front: 'What is the Master Theorem?',
        back: 'The Master Theorem solves recurrences of the form:\nT(n) = aT(n/b) + O(nᶜ)\n\nwhere a ≥ 1, b > 1:\n\nCase 1: c < log_b(a) → T(n) = O(n^(log_b(a)))\nCase 2: c = log_b(a) → T(n) = O(nᶜ log n)\nCase 3: c > log_b(a) → T(n) = O(nᶜ)\n\nExample: Merge Sort T(n) = 2T(n/2) + O(n) → Case 2 → O(n log n)',
        status: 'new',
        bookmarked: false,
      },
    ],
  },
];

// ─── Mock Uploaded Files ──────────────────────────────

export const mockUploads: UploadedFile[] = [
  {
    id: 'upload_001',
    name: 'Physics_Chapter3_Mechanics.pdf',
    type: 'pdf',
    size: 2457600, // ~2.4 MB
    status: 'ready',
    uploadedAt: '2026-06-10T14:00:00Z',
    quizzesGenerated: 2,
    flashcardsGenerated: 8,
  },
  {
    id: 'upload_002',
    name: 'Organic_Chemistry_Notes.pdf',
    type: 'pdf',
    size: 3145728, // ~3 MB
    status: 'ready',
    uploadedAt: '2026-06-08T09:30:00Z',
    quizzesGenerated: 1,
    flashcardsGenerated: 12,
  },
  {
    id: 'upload_003',
    name: 'Calculus_Integration_PPT.ppt',
    type: 'ppt',
    size: 5242880, // ~5 MB
    status: 'processing',
    uploadedAt: '2026-06-16T07:00:00Z',
    quizzesGenerated: 0,
    flashcardsGenerated: 0,
  },
  {
    id: 'upload_004',
    name: 'DSA_Notes_Trees_Graphs.md',
    type: 'md',
    size: 45056, // ~44 KB
    status: 'ready',
    uploadedAt: '2026-06-12T16:00:00Z',
    quizzesGenerated: 1,
    flashcardsGenerated: 6,
  },
  {
    id: 'upload_005',
    name: 'Biology_Diagrams.image',
    type: 'image',
    size: 1048576, // ~1 MB
    status: 'error',
    uploadedAt: '2026-06-15T20:00:00Z',
    quizzesGenerated: 0,
    flashcardsGenerated: 0,
  },
];

// ─── Mock Achievements ────────────────────────────────

export const mockAchievements: Achievement[] = [
  // Unlocked achievements
  {
    id: 'ach_001',
    title: 'First Steps',
    description: 'Complete your first quiz',
    icon: 'Rocket',
    rarity: 'common',
    category: 'quiz',
    requirement: 1,
    progress: 1,
    unlocked: true,
    unlockedAt: '2026-01-16T10:30:00Z',
  },
  {
    id: 'ach_002',
    title: 'Knowledge Seeker',
    description: 'Complete 10 quizzes',
    icon: 'BookOpen',
    rarity: 'common',
    category: 'quiz',
    requirement: 10,
    progress: 10,
    unlocked: true,
    unlockedAt: '2026-02-28T15:00:00Z',
  },
  {
    id: 'ach_003',
    title: 'Perfect Score',
    description: 'Get 100% on any quiz',
    icon: 'Star',
    rarity: 'rare',
    category: 'quiz',
    requirement: 1,
    progress: 1,
    unlocked: true,
    unlockedAt: '2026-03-05T11:00:00Z',
  },
  {
    id: 'ach_004',
    title: 'On Fire!',
    description: 'Maintain a 7-day streak',
    icon: 'Flame',
    rarity: 'rare',
    category: 'streak',
    requirement: 7,
    progress: 7,
    unlocked: true,
    unlockedAt: '2026-06-07T08:00:00Z',
  },
  {
    id: 'ach_005',
    title: 'Card Master',
    description: 'Master 20 flashcards',
    icon: 'Layers',
    rarity: 'common',
    category: 'revision',
    requirement: 20,
    progress: 20,
    unlocked: true,
    unlockedAt: '2026-04-12T14:00:00Z',
  },
  // In-progress achievements
  {
    id: 'ach_006',
    title: 'Quiz Champion',
    description: 'Complete 50 quizzes',
    icon: 'Trophy',
    rarity: 'rare',
    category: 'quiz',
    requirement: 50,
    progress: 47,
    unlocked: false,
  },
  {
    id: 'ach_007',
    title: 'Unstoppable',
    description: 'Maintain a 30-day streak',
    icon: 'Zap',
    rarity: 'epic',
    category: 'streak',
    requirement: 30,
    progress: 12,
    unlocked: false,
  },
  {
    id: 'ach_008',
    title: 'Battle Veteran',
    description: 'Win 10 quiz battles',
    icon: 'Swords',
    rarity: 'rare',
    category: 'battle',
    requirement: 10,
    progress: 6,
    unlocked: false,
  },
  {
    id: 'ach_009',
    title: 'Polymath',
    description: 'Complete quizzes in 5 different subjects',
    icon: 'Brain',
    rarity: 'epic',
    category: 'special',
    requirement: 5,
    progress: 4,
    unlocked: false,
  },
  {
    id: 'ach_010',
    title: 'Legend Status',
    description: 'Reach Level 5 (Legend)',
    icon: 'Crown',
    rarity: 'legendary',
    category: 'special',
    requirement: 7000,
    progress: 2450,
    unlocked: false,
  },
  {
    id: 'ach_011',
    title: 'Revision Pro',
    description: 'Review 100 flashcards in a single day',
    icon: 'RotateCcw',
    rarity: 'epic',
    category: 'revision',
    requirement: 100,
    progress: 34,
    unlocked: false,
  },
  {
    id: 'ach_012',
    title: 'Speed Demon',
    description: 'Complete a quiz in under 60 seconds',
    icon: 'Timer',
    rarity: 'legendary',
    category: 'quiz',
    requirement: 1,
    progress: 0,
    unlocked: false,
  },
];

// ─── Mock Leaderboard ─────────────────────────────────

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1,  userId: 'u_01', name: 'Priya Sharma',     avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Priya',     xp: 8920, level: 5, quizzesCompleted: 142, accuracy: 92 },
  { rank: 2,  userId: 'u_02', name: 'Rahul Krishnan',    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul',     xp: 7840, level: 5, quizzesCompleted: 128, accuracy: 88 },
  { rank: 3,  userId: 'u_03', name: 'Sneha Patel',       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sneha',     xp: 6540, level: 4, quizzesCompleted: 105, accuracy: 85 },
  { rank: 4,  userId: 'u_04', name: 'Vikram Singh',      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Vikram',    xp: 5890, level: 4, quizzesCompleted: 98,  accuracy: 82 },
  { rank: 5,  userId: 'u_05', name: 'Ananya Desai',      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ananya',    xp: 5120, level: 4, quizzesCompleted: 89,  accuracy: 86 },
  { rank: 6,  userId: 'u_06', name: 'Karthik Iyer',      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Karthik',   xp: 4780, level: 4, quizzesCompleted: 82,  accuracy: 79 },
  { rank: 7,  userId: 'u_07', name: 'Meera Nair',        avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Meera',     xp: 4350, level: 4, quizzesCompleted: 76,  accuracy: 84 },
  { rank: 8,  userId: 'u_08', name: 'Aditya Gupta',      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aditya',    xp: 3900, level: 4, quizzesCompleted: 71,  accuracy: 81 },
  { rank: 9,  userId: 'u_09', name: 'Divya Reddy',       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Divya',     xp: 3650, level: 4, quizzesCompleted: 65,  accuracy: 77 },
  { rank: 10, userId: 'u_10', name: 'Rohan Joshi',       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rohan',     xp: 3200, level: 3, quizzesCompleted: 58,  accuracy: 80 },
  { rank: 11, userId: 'u_11', name: 'Ishita Malhotra',   avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ishita',    xp: 2890, level: 3, quizzesCompleted: 53,  accuracy: 76 },
  { rank: 12, userId: 'user_001', name: 'Arjun Mehta',   avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Arjun',     xp: 2450, level: 3, quizzesCompleted: 47,  accuracy: 78 },
  { rank: 13, userId: 'u_13', name: 'Neha Kapoor',       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Neha',      xp: 2200, level: 3, quizzesCompleted: 42,  accuracy: 74 },
  { rank: 14, userId: 'u_14', name: 'Siddharth Rao',     avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Siddharth', xp: 1980, level: 3, quizzesCompleted: 38,  accuracy: 72 },
  { rank: 15, userId: 'u_15', name: 'Tanvi Bhatt',       avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Tanvi',     xp: 1750, level: 3, quizzesCompleted: 34,  accuracy: 75 },
  { rank: 16, userId: 'u_16', name: 'Aman Verma',        avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aman',      xp: 1420, level: 2, quizzesCompleted: 28,  accuracy: 70 },
  { rank: 17, userId: 'u_17', name: 'Kavya Sundaram',    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Kavya',     xp: 1150, level: 2, quizzesCompleted: 22,  accuracy: 68 },
  { rank: 18, userId: 'u_18', name: 'Harsh Agarwal',     avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Harsh',     xp: 890,  level: 2, quizzesCompleted: 18,  accuracy: 65 },
  { rank: 19, userId: 'u_19', name: 'Pooja Thakur',      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Pooja',     xp: 620,  level: 2, quizzesCompleted: 12,  accuracy: 71 },
  { rank: 20, userId: 'u_20', name: 'Dev Kulkarni',      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Dev',       xp: 340,  level: 1, quizzesCompleted: 7,   accuracy: 63 },
];

// ─── Mock Battles ─────────────────────────────────────

export const mockBattles: Battle[] = [
  {
    id: 'battle_001',
    opponent: {
      name: 'Sneha Patel',
      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sneha',
      level: 4,
    },
    subject: 'Physics',
    status: 'completed',
    playerScore: 8,
    opponentScore: 6,
    xpReward: 75,
    startedAt: '2026-06-15T16:00:00Z',
  },
  {
    id: 'battle_002',
    opponent: {
      name: 'Karthik Iyer',
      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Karthik',
      level: 4,
    },
    subject: 'Mathematics',
    status: 'in_progress',
    playerScore: 3,
    opponentScore: 4,
    xpReward: 75,
    startedAt: '2026-06-16T07:30:00Z',
  },
  {
    id: 'battle_003',
    opponent: {
      name: 'Divya Reddy',
      avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Divya',
      level: 4,
    },
    subject: 'Chemistry',
    status: 'waiting',
    playerScore: 0,
    opponentScore: 0,
    xpReward: 75,
    startedAt: '2026-06-16T07:45:00Z',
  },
];

// ─── Mock Revision Topics ─────────────────────────────

export const mockRevisionTopics: RevisionTopic[] = [
  {
    id: 'rev_001',
    name: "Newton's Laws",
    subject: 'Physics',
    strength: 85,
    lastRevised: '2026-06-15T10:00:00Z',
    nextRevision: '2026-06-18T10:00:00Z',
    questionsAttempted: 42,
    accuracy: 88,
  },
  {
    id: 'rev_002',
    name: 'Thermodynamics',
    subject: 'Physics',
    strength: 62,
    lastRevised: '2026-06-12T14:00:00Z',
    nextRevision: '2026-06-16T14:00:00Z',
    questionsAttempted: 28,
    accuracy: 68,
  },
  {
    id: 'rev_003',
    name: 'Organic Reactions',
    subject: 'Chemistry',
    strength: 45,
    lastRevised: '2026-06-10T09:00:00Z',
    nextRevision: '2026-06-16T09:00:00Z',
    questionsAttempted: 35,
    accuracy: 54,
  },
  {
    id: 'rev_004',
    name: 'Chemical Bonding',
    subject: 'Chemistry',
    strength: 78,
    lastRevised: '2026-06-14T16:00:00Z',
    nextRevision: '2026-06-19T16:00:00Z',
    questionsAttempted: 38,
    accuracy: 82,
  },
  {
    id: 'rev_005',
    name: 'Differential Calculus',
    subject: 'Mathematics',
    strength: 92,
    lastRevised: '2026-06-16T05:00:00Z',
    nextRevision: '2026-06-23T05:00:00Z',
    questionsAttempted: 55,
    accuracy: 94,
  },
  {
    id: 'rev_006',
    name: 'Integral Calculus',
    subject: 'Mathematics',
    strength: 58,
    lastRevised: '2026-06-11T11:00:00Z',
    nextRevision: '2026-06-16T11:00:00Z',
    questionsAttempted: 30,
    accuracy: 63,
  },
  {
    id: 'rev_007',
    name: 'Binary Trees',
    subject: 'Computer Science',
    strength: 73,
    lastRevised: '2026-06-13T18:00:00Z',
    nextRevision: '2026-06-17T18:00:00Z',
    questionsAttempted: 22,
    accuracy: 77,
  },
  {
    id: 'rev_008',
    name: 'Indian Independence',
    subject: 'History',
    strength: 20,
    lastRevised: '2026-06-02T08:00:00Z',
    nextRevision: '2026-06-16T08:00:00Z',
    questionsAttempted: 10,
    accuracy: 40,
  },
];

// ─── Mock Activities (Recent) ─────────────────────────

export const mockActivities: Activity[] = [
  {
    id: 'act_001',
    type: 'quiz_completed',
    title: 'Quiz Completed',
    description: "Scored 87% on Newton's Laws of Motion",
    xp: 75,
    timestamp: '2026-06-16T07:00:00Z',
  },
  {
    id: 'act_002',
    type: 'streak',
    title: '12-Day Streak! 🔥',
    description: 'You\'re on fire! Keep it going!',
    xp: 15,
    timestamp: '2026-06-16T06:30:00Z',
  },
  {
    id: 'act_003',
    type: 'flashcard_reviewed',
    title: 'Flashcards Reviewed',
    description: 'Reviewed 15 cards from Organic Chemistry Reactions',
    xp: 30,
    timestamp: '2026-06-16T06:00:00Z',
  },
  {
    id: 'act_004',
    type: 'battle_won',
    title: 'Battle Won! ⚔️',
    description: 'Defeated Sneha Patel in Physics (8-6)',
    xp: 75,
    timestamp: '2026-06-15T16:30:00Z',
  },
  {
    id: 'act_005',
    type: 'achievement_unlocked',
    title: 'Achievement Unlocked! 🏆',
    description: 'On Fire! — Maintained a 7-day streak',
    xp: 50,
    timestamp: '2026-06-15T08:00:00Z',
  },
  {
    id: 'act_006',
    type: 'quiz_completed',
    title: 'Quiz Completed',
    description: 'Scored 70% on Periodic Table & Elements',
    xp: 50,
    timestamp: '2026-06-14T14:00:00Z',
  },
  {
    id: 'act_007',
    type: 'upload',
    title: 'File Uploaded',
    description: 'Uploaded DSA_Notes_Trees_Graphs.md — 1 quiz generated',
    xp: 20,
    timestamp: '2026-06-14T11:00:00Z',
  },
  {
    id: 'act_008',
    type: 'level_up',
    title: 'Level Up! 🎉',
    description: 'You reached Level 3 — Scholar',
    timestamp: '2026-06-13T09:00:00Z',
  },
  {
    id: 'act_009',
    type: 'quiz_completed',
    title: 'Quiz Completed',
    description: 'Scored 100% on Cell Structure & Function — Perfect!',
    xp: 100,
    timestamp: '2026-06-12T10:00:00Z',
  },
  {
    id: 'act_010',
    type: 'flashcard_reviewed',
    title: 'Flashcards Reviewed',
    description: 'Mastered 3 cards from Mathematical Theorems',
    xp: 30,
    timestamp: '2026-06-11T17:00:00Z',
  },
];

// ─── Weekly Study Data (for Charts) ───────────────────

export const weeklyStudyData: StudyDataPoint[] = [
  { day: 'Mon', studyMinutes: 35, quizzes: 2 },
  { day: 'Tue', studyMinutes: 48, quizzes: 3 },
  { day: 'Wed', studyMinutes: 22, quizzes: 1 },
  { day: 'Thu', studyMinutes: 55, quizzes: 4 },
  { day: 'Fri', studyMinutes: 41, quizzes: 2 },
  { day: 'Sat', studyMinutes: 67, quizzes: 5 },
  { day: 'Sun', studyMinutes: 52, quizzes: 3 },
];

// ─── Accuracy Over Time (for Charts) ─────────────────

export const accuracyOverTime: AccuracyDataPoint[] = [
  { date: 'Week 1',  accuracy: 58 },
  { date: 'Week 2',  accuracy: 62 },
  { date: 'Week 3',  accuracy: 65 },
  { date: 'Week 4',  accuracy: 68 },
  { date: 'Week 5',  accuracy: 71 },
  { date: 'Week 6',  accuracy: 74 },
  { date: 'Week 7',  accuracy: 76 },
  { date: 'Week 8',  accuracy: 78 },
];

// ─── Subject Distribution (for Charts) ────────────────

export const subjectDistribution = [
  { subject: 'Physics',          quizzes: 14, color: '#3b82f6' },
  { subject: 'Chemistry',        quizzes: 11, color: '#22c55e' },
  { subject: 'Mathematics',      quizzes: 12, color: '#8b5cf6' },
  { subject: 'Biology',          quizzes: 5,  color: '#f59e0b' },
  { subject: 'History',          quizzes: 3,  color: '#f43f5e' },
  { subject: 'Computer Science', quizzes: 2,  color: '#06b6d4' },
];
