// ═══════════════════════════════════════════════════════
// CUBA BOARD — Phase 15: Voice Quiz & Speech Synthesis Engine
// Text-to-Speech question reader & Web Speech recognition for hands-free learning
// ═══════════════════════════════════════════════════════

/**
 * Reads text aloud using browser Web Speech Synthesis API
 */
export function speakText(text: string, onEnd?: () => void): void {
  if (!('speechSynthesis' in window)) {
    console.warn('Speech synthesis not supported in this browser.');
    return;
  }

  // Cancel any ongoing speech
  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 1.0;
  utterance.pitch = 1.0;
  utterance.lang = 'en-US';

  if (onEnd) {
    utterance.onend = onEnd;
  }

  window.speechSynthesis.speak(utterance);
}

/**
 * Stops ongoing speech synthesis
 */
export function stopSpeech(): void {
  if ('speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}

/**
 * Converts quiz data into a formatted printable Markdown study guide
 */
export function exportQuizToMarkdown(quizTitle: string, questions: Array<{ text: string; options: string[]; correctAnswer: number; explanation: string }>): string {
  let md = `# Cuba Board Study Guide: ${quizTitle}\n\n`;
  md += `*Generated by Cuba Board AI — ${new Date().toLocaleDateString()}*\n\n---\n\n`;

  questions.forEach((q, idx) => {
    md += `### Q${idx + 1}. ${q.text}\n\n`;
    q.options.forEach((opt, oIdx) => {
      const isCorrect = oIdx === q.correctAnswer;
      md += `- [${isCorrect ? 'X' : ' '}] Option ${oIdx + 1}: ${opt}${isCorrect ? ' **(Correct Answer)**' : ''}\n`;
    });
    md += `\n> **Explanation:** ${q.explanation}\n\n---\n\n`;
  });

  return md;
}

/**
 * Triggers a browser file download for text/markdown content
 */
export function downloadFile(filename: string, content: string, mimeType = 'text/markdown'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
