// ═══════════════════════════════════════════════════════
// CUBA BOARD — Public Study & Quiz Marketplace
// Browse community study guides, top-rated quizzes, & shared flashcards
// ═══════════════════════════════════════════════════════

import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Star, Download, Bookmark, Sparkles, Filter, ChevronRight } from 'lucide-react';
import { Badge } from '@/components/ui';

interface PublicMaterial {
  id: string;
  title: string;
  creator: string;
  subject: string;
  rating: number;
  downloads: number;
  questionCount: number;
  type: 'Quiz' | 'Flashcard Deck' | 'Study Summary';
  tags: string[];
}

const mockMarketplace: PublicMaterial[] = [
  { id: 'p1', title: 'Complete GATE CS Operating Systems Master Guide', creator: 'Vikram S.', subject: 'Computer Science', rating: 4.9, downloads: 1420, questionCount: 25, type: 'Quiz', tags: ['GATE', 'OS', 'Scheduling'] },
  { id: 'p2', title: 'Organic Chemistry Reactions Cheat Deck', creator: 'Ananya D.', subject: 'Chemistry', rating: 4.8, downloads: 980, questionCount: 40, type: 'Flashcard Deck', tags: ['Chemistry', 'NEET', 'Reactions'] },
  { id: 'p3', title: 'Quantum Mechanics Core Formulas & Concept Summary', creator: 'Dr. Mehta', subject: 'Physics', rating: 5.0, downloads: 2150, questionCount: 15, type: 'Study Summary', tags: ['Physics', 'Quantum', 'University'] },
  { id: 'p4', title: 'Linear Algebra Vector Spaces & Matrices Drill', creator: 'Rahul K.', subject: 'Mathematics', rating: 4.7, downloads: 760, questionCount: 20, type: 'Quiz', tags: ['Math', 'Vectors', 'JEE'] },
];

const Marketplace: React.FC = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');

  const categories = ['All', 'Computer Science', 'Physics', 'Chemistry', 'Mathematics'];

  const filtered = mockMarketplace.filter((item) => {
    const matchesCategory = selectedCategory === 'All' || item.subject === selectedCategory;
    const matchesSearch = item.title.toLowerCase().includes(searchTerm.toLowerCase()) || item.tags.some(t => t.toLowerCase().includes(searchTerm.toLowerCase()));
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      {/* Hero Search Header */}
      <div className="card bg-gradient-to-r from-primary/20 via-purple-950/40 to-surface p-8 rounded-3xl border border-white/10 relative overflow-hidden text-center space-y-6">
        <div className="max-w-2xl mx-auto">
          <Badge variant="electric" className="mb-3">
            <Sparkles className="w-3.5 h-3.5 mr-1" />
            Community Knowledge Hub
          </Badge>
          <h1 className="text-3xl sm:text-4xl font-black text-white">Public Study & Quiz Marketplace</h1>
          <p className="text-gray-300 text-sm mt-2">Discover, bookmark, and practice top-rated quizzes and flashcard decks generated by Cuba Board learners.</p>
        </div>

        {/* Search Bar */}
        <div className="max-w-xl mx-auto relative">
          <Search className="w-5 h-5 text-gray-400 absolute left-4 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search topics, subjects, or keywords (e.g. Operating Systems, Chemistry)..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-surface/90 text-white pl-12 pr-4 py-3.5 rounded-2xl border border-white/10 focus:border-primary outline-none text-sm shadow-xl"
          />
        </div>
      </div>

      {/* Subject Filter Pills */}
      <div className="flex items-center justify-between flex-wrap gap-4 border-b border-white/5 pb-4">
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-gray-400" />
          <span className="text-xs text-gray-400 font-bold uppercase tracking-wider">Category:</span>
        </div>
        <div className="flex gap-2">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all border ${
                selectedCategory === cat
                  ? 'bg-primary border-primary text-white shadow-lg'
                  : 'bg-surfaceHover border-white/5 text-gray-400 hover:text-white'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Grid of Materials */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filtered.map((item) => (
          <div key={item.id} className="card bg-surface border border-white/5 hover:border-primary/30 p-6 rounded-2xl flex flex-col justify-between transition-all group">
            <div className="space-y-4">
              <div className="flex justify-between items-start">
                <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 uppercase tracking-wider">
                  {item.subject} &bull; {item.type}
                </span>
                <div className="flex items-center gap-1 text-gold text-xs font-bold font-mono">
                  <Star className="w-3.5 h-3.5 fill-gold text-gold" />
                  {item.rating}
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-white group-hover:text-primary transition-colors leading-snug">{item.title}</h3>
                <p className="text-xs text-gray-400 mt-1">Created by <strong className="text-white">{item.creator}</strong> • {item.questionCount} Questions</p>
              </div>

              <div className="flex flex-wrap gap-1.5 pt-2">
                {item.tags.map((tag, i) => (
                  <span key={i} className="px-2 py-0.5 bg-surfaceHover text-gray-400 rounded-md text-[10px] font-medium border border-white/5">
                    #{tag}
                  </span>
                ))}
              </div>
            </div>

            <div className="flex items-center justify-between border-t border-white/5 pt-4 mt-6">
              <div className="flex items-center gap-1.5 text-xs text-gray-400 font-mono">
                <Download className="w-3.5 h-3.5 text-primary" />
                {item.downloads.toLocaleString()} Studies
              </div>

              <button
                onClick={() => navigate('/upload')}
                className="px-4 py-2 bg-primary/10 hover:bg-primary text-primary hover:text-white rounded-xl text-xs font-bold transition-all border border-primary/20 flex items-center gap-1"
              >
                Import & Study
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Marketplace;
